project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: right
    linkcolor: "green"
    theme: 
      - zephyr
      - custom.scss
website:
  navbar:
    search: true
    # logo: "./assets/icon.png"
    title: Guía de web scraping con Data Miner ⚒️
    background: "primary"
  page-footer: 
    border: false
    background: dark
    foreground: "#ffffff"
    left: >
      Created by Fernanda Aguirre Ruíz
    center:
      - icon: github
        href: https://github.com/fer-aguirre
      - icon: twitter 
        href: https://twitter.com/feragru
      - icon: linkedin
        href: https://www.linkedin.com/in/feragru/
      - icon: envelope
        href: mailto:feraguirre@riseup.net
    right: >
        [Powered by Quarto](https://github.com/fer-aguirre/oportunidades-perioidstas-latam)

